/* Fixed builds for every lesson. These append to the original exercise list so
   saved answers for gate-chain remain valid. */
(function(){
  if(typeof EXERCISES==="undefined")return;
  var specs=[
    {id:"file-map",unit:"w1",title:"Make your first file map",mins:"20 min",goal:"Create a plain-text .json file in the correct folder and describe its full path.",guided:"Finder -> study folder -> example.json. The folder is the container; example.json is the file; .json is the extension.",task:"Create practice-profile.json in your study folder using TextEdit in plain-text mode. Put only your name and study goal inside it as valid JSON. Then write the full path here.",hints:["First open the study folder in Finder.","In TextEdit choose Format > Make Plain Text before saving.",'Use { "name": "Learner", "goal": "study CCA-F" } and make sure the filename ends only in .json.'],verify:"In Finder, confirm the Kind/extension is JSON or the name ends in .json, not .json.txt. Open it again and confirm the text is unchanged.",explain:"In your own words, explain file vs folder vs path vs extension.",expected:"A real plain-text practice-profile.json file, a plausible full path, and no hidden .txt ending."},
    {id:"json-card",unit:"w2",title:"Build and repair a JSON card",mins:"20 min",goal:"Write one valid JSON object, then deliberately find and repair syntax errors.",guided:'Valid: { "item": "tea", "quantity": 2, "urgent": false }. Keys and text use straight double quotes; commas separate pairs; no comma follows the last pair.',task:'Write a new object for a book with title, pages, topics (an array), and available (true/false). Do not copy the guided values.',hints:["Start with opening and closing braces.","Add one quoted key, a colon, and one value at a time.",'Array example: "topics": ["AI", "tools"].'],verify:"Paste your object into a JSON validator or ask your tutor to parse it. Record the exact error if it fails, then repair it.",explain:"Why can JSON be syntactically valid but still contain a wrong fact?",expected:"A valid object with four requested fields, a real validation attempt, and a distinction between syntax and truth."},
    {id:"function-machine",unit:"w3",title:"Trace a tiny function machine",mins:"20 min",goal:"Follow inputs through a named action to an output and one clear error.",guided:"price_with_tax(10, 0.10) -> multiply 10 by 0.10 -> add 1 -> return 11.",task:"Design a function called shipping_cost(weight, speed). Give one normal input and return value. Then give one invalid input and the exact error it should produce.",hints:["Arguments are the values inside the parentheses.","Write the happy path before the error path.","A useful error names the bad input and what was expected."],verify:"Ask: can another person predict the return value from your rule? Can they tell how to repair the invalid input from your error?",explain:"Explain argument, function, return value, and error using your example.",expected:"A named function, inputs, deterministic rule, output, and specific invalid-input error."},
    {id:"api-envelope",unit:"w4",title:"Pack an API request envelope",mins:"20 min",goal:"Label a complete request and response without writing code.",guided:"App -> GET /orders/42 with Authorization header -> Order API -> 200 -> { order_id: 42, status: shipped }.",task:"Design a request for a weather API. Write method, path, one non-secret input, where the API key comes from, success status/body, and one error status/body.",hints:["GET is a good method for reading data.","Put location in the path or query, not in the secret.","Say API_KEY environment variable; never write a real key."],verify:"Trace it aloud: client sends what, server returns what, and where does the secret stay?",explain:"Explain request vs response and why the key stays outside the file.",expected:"A labeled request and response, meaningful statuses, and the key referenced only as an environment variable."},
    {id:"terminal-simulator",unit:"w5",title:"Run a safe Terminal inspection",mins:"20 min",goal:"Use look-only commands to identify your working directory and inspect one file.",guided:"pwd shows where you are. ls shows nearby names. cd moves to a known folder. pwd confirms the move. cat reads a small plain-text file.",task:"In Terminal, run pwd. Navigate to your study folder using cd with a quoted path. Run pwd again, then ls. Record the commands and the important output. Do not delete, install, or overwrite anything.",hints:["Open Terminal from Applications > Utilities.","A path with spaces needs quotes: cd \"/path/with spaces\".","If cd fails, copy the exact error; do not guess with risky commands."],verify:"The final pwd should name the study folder, and ls should include course files. Record the exit/error message if it does not.",explain:"Why should you run pwd before a file-changing command?",expected:"A safe command transcript using pwd, cd, pwd, ls with no destructive command."},
    {id:"vocabulary-flow",unit:"a1",title:"Label the Claude request flow",mins:"20 min",goal:"Place the core vocabulary on one concrete request-response picture.",guided:"User prompt -> API request as JSON -> model reads tokens inside its context window -> response. A schema may constrain output; a tool may be requested.",task:"Draw five boxes for a restaurant-booking request. Label prompt, API, JSON, model, context window, tool, schema, and token in the correct places.",hints:["The prompt is inside the request.","JSON is the data format, not the API itself.","A tool is an outside action the model may request."],verify:"Point to every term without reading your notes. If a term has no place, revise the drawing.",explain:"Explain the entire flow in four sentences without defining terms in a list.",expected:"One coherent flow using all eight words in technically sensible places."},
    {id:"prompt-clinic",unit:"m3",title:"Repair a vague prompt",mins:"25 min",goal:"Turn an unreliable request into a prompt with criteria, examples, and output format.",guided:"Vague: Review this ticket. Better: classify billing/bug/account; quote one clue; output JSON; if ambiguous use needs_review. Include one clear and one ambiguous example.",task:"Rewrite: 'Check this customer email and tell me if it is urgent.' Define urgent, show two examples, require a small output shape, and say what to do when uncertain.",hints:["List observable urgency signals.","Include one tricky example near the boundary.","Use fields such as label, evidence, and needs_review."],verify:"Test your prompt on one obvious email and one ambiguous email. Record where it behaves differently from the vague version.",explain:"Which part reduces false positives most, and why?",expected:"Explicit criteria, two targeted examples, fixed output fields, and an uncertainty route."},
    {id:"schema-lab",unit:"m1",title:"Design a small extraction schema",mins:"25 min",goal:"Create a schema that is strict about shape and honest about missing facts.",guided:'Invoice fields: invoice_id string required; due_date string or null; category enum [software, travel, other]; category_detail string or null.',task:"Design fields for a support ticket: customer_id, issue_type, issue_detail, order_id, and needs_human. Mark required, nullable, type, and allowed enum values.",hints:["A missing real-world fact should usually be nullable, not invented.","Use other plus a detail field when categories may grow.","Required means the key must exist; nullable means its value may be null."],verify:"Test three cases: complete ticket, missing order ID, and new issue type. Explain how each fits without hallucination.",explain:"Why does schema-valid not mean factually correct?",expected:"A usable field table with types, required/nullable choices, extensible enum, and three edge-case checks."},
    {id:"tool-call-envelope",unit:"m2",title:"Complete one tool-call envelope",mins:"25 min",goal:"Write the five handoffs in a real tool call, including an error path.",guided:"Tool definition -> model tool_use -> application runs action -> tool_result -> model final answer. Claude requests; application executes.",task:"Design get_order_status(order_id). Write its name, clear description, input schema, one tool_use request, one success tool_result, and one is_error result for a timeout.",hints:["The description should say when to use the tool.","tool_use contains the tool name and input.","The failure result needs is_error: true and a specific message."],verify:"Underline who performs each step. If Claude appears to run the database itself, repair the flow.",explain:"What should the model do after the success result? What can it do after the error result?",expected:"All five handoffs, correct executor, clear input, success result, and specific is_error path."},
    {id:"agent-loop-board",unit:"o1",title:"Run an agent loop on paper",mins:"25 min",goal:"Trace repeated model and tool turns until stop_reason ends the loop.",guided:"Model asks lookup_order, stop_reason tool_use -> app runs tool -> result returns -> model asks refund, tool_use -> app runs -> result -> model explains outcome, end_turn.",task:"Create a three-turn loop for planning a calendar meeting. Include at least two tool requests, their results, every stop_reason, one hard safety limit, and the final end_turn.",hints:["The application reads stop_reason after every model response.","Each tool_result becomes context for the next model turn.","A hard cap is a backup guard, not the primary success signal."],verify:"Follow only the stop_reason fields. Can your application tell continue from done without reading prose?",explain:"Why is this an agent rather than a fixed workflow? When would one call be enough?",expected:"A correct alternating loop with tool_use continuation, end_turn completion, and one guardrail."},
    {id:"model-router",unit:"a2",title:"Route three jobs to the right lane",mins:"20 min",goal:"Choose model strength, caching, and batch/real-time mode from task constraints.",guided:"Daily extraction: fast model + cached policy + batch. Live safety-sensitive planning: stronger model + real-time + human gate.",task:"Decide for: 10,000 overnight invoice extractions; a live password-reset router; a monthly architecture synthesis. For each choose model tier, real-time/batch, caching, and one tradeoff.",hints:["Start with urgency: can the result wait?","Then task difficulty: extraction is bounded; synthesis is harder.","Cache a stable prefix such as policy or schema."],verify:"Defend every expensive choice. If a cheaper path meets the constraint, revise.",explain:"Why is 'always use the strongest model' weak architecture?",expected:"Three defensible routes tied to urgency, difficulty, repeated context, cost, and latency."},
    {id:"diff-reader",unit:"d1",title:"Read a diff before judging it",mins:"20 min",goal:"Identify added, removed, and unchanged behavior in a tiny project change.",guided:"- timeout = 5 means removed. + timeout = 15 means added. The behavior changed from five seconds to fifteen.",task:"Write a four-line before/after example for a refund limit. Turn it into a mini diff with - and +. State the behavior change and one nearby file you would inspect for context.",hints:["Keep one unchanged line for orientation.","Minus is old; plus is new.","A test or caller is useful surrounding context."],verify:"A reader should reconstruct the old and new rule from your diff.",explain:"Why can a correct-looking changed line still break another file?",expected:"A coherent mini diff, accurate behavior summary, and one sensible context check."},
    {id:"pr-paper-sim",unit:"d2",title:"Move one change through a pull request",mins:"25 min",goal:"Simulate branch, commit, PR, CI, review, and merge with a tiny change.",guided:"branch fix/title -> edit -> commit 'Clarify page title' -> PR explains why -> CI checks links -> reviewer approves -> merge.",task:"Plan a change that fixes one broken course link. Name the branch, files changed, commit message, PR summary, two CI checks, one reviewer question, and merge condition.",hints:["A branch name should be short and specific.","A commit message says what changed, not 'stuff'.","CI can check syntax and links; a human checks intent."],verify:"Trace the order. Nothing merges before checks and review conditions are met.",explain:"What does green CI prove, and what does it not prove?",expected:"A complete ordered PR flow with meaningful names, checks, review, and a cautious conclusion."},
    {id:"tool-picker",unit:"m4",title:"Choose the safest built-in tool",mins:"20 min",goal:"Match six codebase tasks to Read, Edit, Grep, Glob, Bash, or Write.",guided:"Find text in unknown files -> Grep. Match all test filenames -> Glob. Inspect a known file -> Read.",task:"Choose a tool and reason for: find TODO text; list *.test.js paths; inspect config.js; replace one unique line; create a new report file; run tests.",hints:["Content search and filename search are different.","Use Edit only when the target text is unique.","Bash runs a command; it is not the default file reader."],verify:"For each choice, name one risk of using a broader tool.",explain:"Describe the explore pattern: Grep an entry point, then Read to follow imports.",expected:"Six correct tool choices with a safety or precision reason."},
    {id:"mcp-menu",unit:"o3",title:"Design an MCP capability menu",mins:"25 min",goal:"Separate actions, read-only context, and user-selected workflows.",guided:"refund_order = tool; policy://returns = resource; investigate-refund = prompt.",task:"Design an MCP server for a library. Add two tools, two resources, and one prompt. Name who controls each, choose stdio or Streamable HTTP, and state how secrets are supplied.",hints:["A resource should not change anything.","A prompt is a reusable workflow the user chooses.","Local single-client tools often fit stdio; remote services may need HTTP."],verify:"Try to misuse each resource as an action. If it can mutate state, reclassify it.",explain:"Why should a read-only catalog be a resource instead of a tool?",expected:"Correct capability types, control owners, transport rationale, and environment-based secret handling."},
    {id:"claude-code-blueprint",unit:"o4",title:"Place Claude Code controls",mins:"25 min",goal:"Put durable guidance, reusable procedures, workers, and hard rules in the right layer.",guided:"Style guidance -> CLAUDE.md. Reusable deploy workflow -> skill. Fresh research slice -> subagent. Block secret commits -> PreToolUse hook.",task:"For a small web project, write one CLAUDE.md rule, outline one skill, define one subagent prompt with tools, choose one hook, and name one headless claude -p job.",hints:["CLAUDE.md guides but does not deterministically enforce.","A subagent receives fresh context, so pass paths and goal.","A rule that must never be broken belongs in code or a hook."],verify:"For each item ask: guidance, reusable workflow, delegated context, or deterministic gate?",explain:"Why is a polite prompt not enough for a critical safety rule?",expected:"Five controls placed at the correct layer with clear reasons."},
    {id:"orchestrator-board",unit:"o2",title:"Delegate a research question",mins:"25 min",goal:"Let a coordinator choose distinct workers, pass context, and synthesize sourced findings.",guided:"Coordinator receives EV-market question -> battery worker + charging worker + policy worker -> findings -> dedupe/gap check -> synthesis.",task:"Plan research on AI tutoring for dyslexic adults. Choose three distinct worker scopes, write each worker's context packet, define the finding format, and add a second-round gap rule.",hints:["Worker scopes should not ask the same search question.","Fresh workers need goal, scope, date range, source rules, and output shape.","Finding = claim + source + date + confidence."],verify:"Check overlap, missing subtopics, and whether the coordinator can verify every claim.",explain:"How does this differ from fixed parallelization? When is multi-agent not worth the cost?",expected:"Dynamic decomposition, explicit packets, inspectable findings, synthesis, and a cost-aware stop rule."},
    {id:"reliability-lab",unit:"rel",title:"Break and repair one agent",mins:"30 min",goal:"Map failures to detection, recovery, and human escalation.",guided:"Timeout -> is_error + category -> bounded backoff retry -> fallback source -> human if still unresolved. Log every attempt.",task:"Design a reliability table for five failures: tool timeout, invalid JSON, missing fact, conflicting sources, and risky action. For each write detection, automated recovery, stop condition, evidence logged, and human route.",hints:["Different failure classes need different handling.","A missing fact is not repaired by repeating the same prompt.","Confidence alone must not control risky escalation."],verify:"Run one saved test case through every row. Mark which checks are code, visual, or LLM-judge.",explain:"Why are evals saved cases plus rubrics rather than 'it worked once'?",expected:"Five distinct routes, bounded retries, provenance, deterministic safety, and a reusable eval case."},
    {id:"support-blueprint",unit:"t1",title:"Blueprint a support agent",mins:"30 min",goal:"Combine loop, scoped tools, deterministic limits, normalization, and handoff.",guided:"Message -> classify issues -> parallel lookups -> normalized results -> refund gate -> response or structured human handoff.",task:"Design an agent for late delivery plus duplicate charge. List tools, split independent checks, place a refund limit, normalize one mixed format, and define handoff fields.",hints:["The refund limit must be deterministic.","Independent lookups may run in parallel, then merge one response.","A handoff should include customer ID, root cause, evidence, and recommendation."],verify:"Trace a refund above the limit and an explicit 'human please' request. Both must reach a person correctly.",explain:"Which controls are prompts, which are hooks/code, and why?",expected:"End-to-end support flow with safe limits, explicit escalation, normalized results, and structured handoff."},
    {id:"research-blueprint",unit:"t2",title:"Blueprint a research system",mins:"30 min",goal:"Plan two research rounds that produce auditable, deduplicated findings.",guided:"Question -> coordinator plan -> distinct source workers -> finding records -> dedupe -> gap analysis -> second round -> synthesis with citations.",task:"Design research for choosing a beginner AI course. Define three source slices, worker packets, finding schema, dedupe rule, gap trigger, and final synthesis checklist.",hints:["Use different source types as well as topics.","Require source URL, publication date, and confidence with every claim.","Second-round work should target a named gap, not restart everything."],verify:"Pick one final claim and trace it back to one source record and worker scope.",explain:"Name one reason this should stay one agent and one reason to use multiple agents.",expected:"Distinct research lanes, provenance, dedupe, adaptive second round, and cost-aware architecture choice."},
    {id:"scenario-decision",unit:"p1",title:"Write an architecture decision record",mins:"25 min",goal:"Choose an approach from constraints and defend it like a production architect.",guided:"Constraint: live risky refunds. Choice: one support agent with scoped tools plus deterministic refund hook and human approval. Tradeoff: slower high-risk cases for safety.",task:"Scenario: overnight review of 20,000 support transcripts must find policy violations with sources; results can wait until morning. Choose architecture, model strategy, batch/real-time, verification, and human route.",hints:["Lead with constraints before naming technology.","Non-urgent bulk work suggests batch.","Policy findings need provenance and sampled human review."],verify:"Name one simpler alternative and explain exactly why it fails a constraint or why it may be better.",explain:"Give your decision in 60 seconds: choice, reason, tradeoff, failure mode, control.",expected:"Constraint-led choice with batch economics, provenance, evals, and human review."},
    {id:"anti-pattern-repair",unit:"px",title:"Repair five tempting designs",mins:"25 min",goal:"Replace classic wrong answers with reliable controls.",guided:"Bad: stop when model says 'done.' Repair: read stop_reason. Bad: prompt says never refund over limit. Repair: deterministic hook/code gate.",task:"Repair five: fixed 5-turn success rule; generic 'try again' retry; 18 overlapping tools; same-session self-review; escalation based only on angry sentiment.",hints:["State the failure before the repair.","Use specific validation errors and bounded retries.","Escalation follows complexity, risk, uncertainty, and explicit request."],verify:"For each repair, name one test that proves the old failure is blocked.",explain:"Why do attractive shortcuts become production anti-patterns?",expected:"Five accurate repairs with failure mechanism and a concrete regression test."},
    {id:"capstone-scope",unit:"p2",title:"Scope the PR-review capstone",mins:"35 min",goal:"Define the smallest real pipeline you can finish and verify end to end.",guided:"Changed files -> per-file claude -p -> JSON validation -> integration pass -> deterministic secret gate -> human review -> comments with file/line provenance.",task:"Choose one narrow review rule. Draw the pipeline, define JSON fields, write one per-file criterion, one integration check, one code guardrail, one human route, and the first end-to-end test.",hints:["One narrow path is enough for version one.","Every finding needs file, line, issue, evidence, and severity.","Put an irreversible or safety-critical block outside the model prompt."],verify:"Run one tiny changed file through the blueprint on paper. Every box must receive and emit a named artifact.",explain:"What can fail, how is it caught, and what happens next?",expected:"A finishable scope, two passes, validated output, deterministic guardrail, provenance, and human review."}
  ];

  function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}
  function make(s){
    return {
      id:s.id,units:[s.unit],icon:"Build:",title:s.title,mins:s.mins,level:"Beginner path | fixed build",goal:s.goal,
      why:"This build is tied to the lesson. It will not ask for a concept that has not appeared in the prerequisites.",
      steps:[
        {h:"1. Study the worked example",body:"<b>Worked example:</b> "+esc(s.guided)},
        {h:"2. Do the independent version",body:esc(s.task),hints:s.hints,field:{id:"independent",label:"Your independent version",ph:"Write or paste your work here."}},
        {h:"3. Verify it",body:esc(s.verify),hints:["Use the named check, not 'it looks right.'","Copy the exact result or error.","If it fails, make one repair and verify again."],field:{id:"verification",label:"Verification evidence",ph:"What did you check? What happened?"}},
        {h:"4. Explain it in your own words",body:esc(s.explain),field:{id:"ownwords",label:"Your explanation",ph:"In my own words..."}}
      ],
      quiz:{title:"Understanding check",intro:"Answer from your build, not from memory alone.",questions:[
        {id:"q1",q:"What did you build, in one sentence?",ph:"I built..."},
        {id:"q2",q:"What evidence shows it worked or is correct?",ph:"My evidence is..."},
        {id:"q3",q:"What is one failure or edge case?",ph:"One failure is..."}
      ]},
      rubric:[s.expected,"The verification names a real check and its result, not only 'looks good.'","The explanation uses the learner's own words and names one failure or edge case.","Independent mastery requires doing the task without copying the worked example's values."]
    };
  }
  var have={};EXERCISES.forEach(function(e){have[e.id]=true;});
  specs.forEach(function(s){if(!have[s.id])EXERCISES.push(make(s));});
})();
